name: Smoke check
run-name: Smoke check - ${{ github.event_name == 'pull_request' && format('PR {0}', github.event.pull_request.number) || github.event_name == 'push' && 'Push' || format('Requested by @{0}', github.actor) }}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: ./.github/workflows/setup-bun.yml
      - run: bun lint:ci

  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: ./.github/workflows/setup-bun.yml
      - run: bun lint:tsc

  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: ./.github/workflows/setup-bun.yml
      - run: bun lint:markdown

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-bun.yml
      - run: bun test

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/dependency-review-action@4081bf99e2866ebe428fc0477b69eb4fcda7220a # v4.4.0
